### ISSUE TITLE
Not showing hologram

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/WildLoaders#10]
After using version b8 the holograms after server restarting were dissapeared. Look on photo for example
![image](https://user-images.githubusercontent.com/76651966/112757019-14dacb80-8fe8-11eb-84e0-8d9bc4690c57.png)

After destroying and placing again it's look like this
![image](https://user-images.githubusercontent.com/76651966/112757032-258b4180-8fe8-11eb-9365-e25af6823e54.png)

**Comment by OmerBenGera** [comment]
It works fine for me - look for errors or something.
Also, you might have a plugin that removes armor stands

**Comment by OmerBenGera** [comment]
Any news regarding this?
