### ISSUE TITLE
Folia Error (Server Froze)

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildLoaders#101]
### Minecraft's Version

This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)

### Plugin's Version

WildLoaders-2024.1-b25

### Describe the bug

Server Froze after this error

https://pastebin.com/53BSCw07

### To Reproduce

I have no idea. I tried by putting this at a magma farm and let it sit there
server restart 1 time at 6am and this incident happen at like 10am

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
