### ISSUE TITLE
Loader Item Duplication

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildLoaders#102]
### Minecraft's Version

This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)

### Plugin's Version

2024.1-b26

### Describe the bug

When mined in survival it duplicates (one real one as a normal named beacon)

### To Reproduce

just mine the loader in survival

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by YusakiDev** [comment]
It did not duplicate anymore but hologram seems to be stuck

**Comment by OmerBenGera** [comment]
> It did not duplicate anymore but hologram seems to be stuck

What do you mean?
When you break a loader, the hologram will despawn.

**Comment by OmerBenGera** [comment]
> It didnt despawn somehow. Im not sure if it is vecause of cmi hologram. The hologram disappear after relogin. Normal cmi hologram do not inherit this behavior

CMI holograms have nothing to do with this.
If this behavior continues, open a new bug report. Closing this for now :)
