### ISSUE TITLE
Hologram Do not disappear after leader was broken

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildLoaders#103]
### Minecraft's Version

This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)

### Plugin's Version

2024.1-b29

### Describe the bug

Hologram do not disappear after loader break

### To Reproduce

just destroy loader

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
A) Are there any errors when you break a loader?
B) Are you able to replicate it on a server with only WL installed?

**Comment by YusakiDev** [comment]
There is no error when breaking the loader
Yes, I can replicate the issue with only WL installed

**Comment by YusakiDev** [comment]
![javaw_MNk99HwKLO](https://github.com/BG-Software-LLC/WildLoaders/assets/36989640/4f49ab3b-87f3-4b69-9cd5-999c64a13e7e)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
