### ISSUE TITLE
Block entity validation issue

### ISSUE THREAD

**Issue by Eimaen** [BG-Software-LLC/WildLoaders#107]
### Minecraft's Version

Paper version 1.21.1-40-master@2fdb2e9 (2024-08-21T01:35:33Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

WildLoaders 2024.2-b32

### Describe the bug

Setting chunkloader type in config to anything other than `COMMAND_BLOCK` and placing it down throws an exception and makes it non-functional.

### To Reproduce

- Install the plugin on the latest Paper release
- Leave the config as-is (as default type is `BEACON`)
- Place the chunkloader of any type

### Additional Information

[latest.log](https://github.com/user-attachments/files/16713530/latest.log)

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Eimaen** [comment]
Can confirm it works as expected now, thanks!
