### ISSUE TITLE
Place BUG (chunks-spread)

### ISSUE THREAD

**Issue by KernelSy1212** [BG-Software-LLC/WildLoaders#114]
### Minecraft's Version

1.8.9

### Plugin's Version

Latest stable build 2024.3 and Dev Builds #37

### Describe the bug

i set "chunks-spread: true" on true and for me work but for the others players with operator (OP) dosen t work is place a simple 
Beacon

![image](https://github.com/user-attachments/assets/ca27dd08-3d1c-4afc-82e2-bd614c53b2f9)

![image](https://github.com/user-attachments/assets/21fa1165-2e34-40c9-9fb6-6aaf58e76e15)

### To Reproduce

i put chunks-spread: true in config

then i restarted the server

then i gived the beacon to a player

**Comment by OmerBenGera** [comment]
What claiming plugin do you have installed?

**Comment by KernelSy1212** [comment]
SaberFactions

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
