### ISSUE TITLE
Plugin cant be loaded

### ISSUE THREAD

**Issue by fourhundredfour** [BG-Software-LLC/WildLoaders#116]
### Minecraft's Version

Paper 1.21.4

### Plugin's Version

2024.4

### Describe the bug

```
[09:09:59 WARN]: com.bgsoftware.wildloaders.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid bu
iltin nms handlers for the data version: 4189
```

### To Reproduce

Install a fresh instance of PaperMC 1.21.4 and add the plugin

**Comment by OmerBenGera** [comment]
Not supportes yet.
