### ISSUE TITLE
Issue with building due to JDK 16 request.

### ISSUE THREAD

**Issue by andrewkm** [BG-Software-LLC/WildLoaders#121]
### Minecraft's Version

1.21.4

### Plugin's Version

https://github.com/BG-Software-LLC/WildLoaders/commit/ba1a563da36b2d1189ea607eef34c280d4e15b57

### Describe the bug

https://pastebin.com/raw/fVsWcPHP

We are still having an issue building due to it wanting JDK 16, and seeing as it's EOL it's giving us problems setting it up on our jenkins.

Can you please fix with:

https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention

### To Reproduce

Build.

### Additional Information

Refer to https://github.com/BG-Software-LLC/WildLoaders/issues/119 @OmerBenGera

**Comment by OmerBenGera** [comment]
You can still install jdk 16, same as jdk 8 is eol and you can still install it

**Comment by electronicboy** [comment]
JDK 16 is not LTS and is basically no longer shipped by any reputable packager, making it a pain to install versus three lines to configure the convention plugin if you're going to rely on EOL versions in your build; This is vs say, java 8, which is still an LTS, and is so still being shipped by pretty much every vender who deals who deals with shipping packages

**Comment by andrewkm** [comment]
> You can still install jdk 16, same as jdk 8 is eol and you can still install it
> 
> Or, just disable BentoBox from compiling

We build off your public repo, shouldn't be too hard for you to alter 3 lines of code to make this sane to compile.

**Comment by electronicboy** [comment]
Actually, looking at the build logs, bentoworld now compiles against java 17, so there is no need to pull in a EOL JDK for the build; (Also, paperweight needs a bump due to some derp)
