### ISSUE TITLE
Place And Break Loader

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildLoaders#15]
Heloo i use WildLoaders-b9 in 1.12.2, when i place loader it works correctly but when i break it and place the same loader on the same block the loader not works correctly and i have to place it in an other location.

**Comment by OmerBenGera** [comment]
Next time use the format. I will take a look into that.

**Comment by nivcoo** [comment]
Yes sorry for the format

**Comment by OmerBenGera** [comment]
Sorry for the long waiting time, it's fixed in latest dev build
