### ISSUE TITLE
Loader players being shown on tab/player count

### ISSUE THREAD

**Issue by Longehh** [BG-Software-LLC/WildLoaders#16]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.8.8 R3 (WineSpigot)

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Latest

**Describe the bug**
Loader Players being shown on the player count/tablist

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

We're using TAB v1.8.10 if it's an issue with that?

**Comment by OmerBenGera** [comment]
Try replicating the issue on regular spigot / paper
