### ISSUE TITLE
Destroying Loaders gives Beacons

### ISSUE THREAD

**Issue by ProfLinebeck** [BG-Software-LLC/WildLoaders#17]
**Minecraft's Version**
Spigot 1.16.5

**Plugin's Version**: -
Latest Dev Build (b12)

**Describe the bug**
Not sure if this is cause of a conflict with other plugins, but when i am going to mine/destroy the Loader, it becomes an Beacon and will stay a Beacon(Chunk loader items is gone and replaced by the Beacon)

**To Reproduce**
Place a chunkloader and destroy it -> You will get a Beacon

**Comment by OmerBenGera** [comment]
Try it using the latest dev build. If it still doesn't work, try it on a server with only WildLoaders installed, so we know if it's due to a conflict with another plugin or not.

**Comment by Virologicbody** [comment]
Same issue on 1.17 Paper Build 43 (latest at this time) with no other plugins installed.

**Comment by Virologicbody** [comment]
Same issue using the latest dev build and Paper 1.17 build 43 with no other plugins installed.

Both WildLoader and Paper build were latest at the time of this post.

**Comment by OmerBenGera** [comment]
As I said before, please try it on a server with only WildLoaders installed on your server.

**Comment by Virologicbody** [comment]
I did try this with no other plugins installed.

Tried it again with dev build 14 (fix for BlockPlaceEventError) and the loader now stays as a loader.. does not return to a beacon.

Now works correctly for me on Paper 1.17 build 46, but would suggest it needs testing on other versions/servers.

**Comment by Virologicbody** [comment]
Ran a Paper 1.16.5 build 670 server all night. Plugin worked (for me) as intended.

**Comment by OmerBenGera** [comment]
The issue was due to the loaders not being registered as a loader correctly.
It's patched in latest dev build :)
