### ISSUE TITLE
It's not working on paper 1.17

### ISSUE THREAD

**Issue by Fighter20000** [BG-Software-LLC/WildLoaders#19]
**Minecraft's Version**
![image](https://user-images.githubusercontent.com/50296138/122672939-72894900-d1ce-11eb-8d86-8dc041384683.png)

**Plugin's Version**: -
![image](https://user-images.githubusercontent.com/50296138/122672951-83d25580-d1ce-11eb-8aad-c927bdc65b27.png)

**Describe the bug**
https://pastebin.com/v6dNW0mk

**To Reproduce**
When I place a beacon!

**Additional information**
I use the default config.

**Comment by OmerBenGera** [comment]
Fixed in build 13.
