### ISSUE TITLE
mstp get absurdly high and server resources don't even reach the limit when I put a chunk loader

### ISSUE THREAD

**Issue by rafael01010** [BG-Software-LLC/WildLoaders#21]
### Minecraft's Version

paper-1.17.1-127

### Plugin's Version

#14 25/06/2021 14:05:39

### Describe the bug

when I put a chunk loader the mstp simply go up a lot and when I go to see the server state it's normal and this causes lag 
im see tps use tabtps plugin

### To Reproduce

1. place a beacon and play game

### Additional Information

plugins im use:
AcceptTheRules*, DriveBackupV2, HomeSpawn, OpeNLogin, SimpleTpa*, SinglePlayerSleep, SkinsRestorer, TabTPS, WildLoaders

**Comment by OmerBenGera** [comment]
What is mstp?

**Comment by rafael01010** [comment]
Mstp is mile second per tick 
use tab tps you see

**Comment by OmerBenGera** [comment]
> Mstp is mile second per tick
> use tab tps you see

I dont know what it is or what it tracks.
If you believe there are performance issues with the plugin, take a spark profiler and send it here (google "spigot spark" and download that plugin)

**Comment by rafael01010** [comment]
want to enter the server to see

**Comment by OmerBenGera** [comment]
I dont have the time to do that, sorry.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by rafael01010** [comment]
problem and version and not plugin 1.17 consumes a lot of resources
