### ISSUE TITLE
Spawners not being loaded in hole chunk Y1-Y256

### ISSUE THREAD

**Issue by Thefluffypvper1** [BG-Software-LLC/WildLoaders#29]
### Minecraft's Version

Winespigot 1.8.8

### Plugin's Version

WildLoaders-b16.jar

### Describe the bug

Spawners are not being loaded for the hole chunk.

### To Reproduce

A player on my server has a skeleton and villager spawner at Y 249 and a blaze spawner at Y 20, the chunkloader is at Y 250 loading the top spawners, but its not loading the blazes at Y 20 when it should be.

### Additional Information

N/A

**Comment by Thefluffypvper1** [comment]
I have the cloudspawners API msg me on discord Thefluffypvper#4520 if you need it

**Comment by OmerBenGera** [comment]
Try using paper, let me know if the issue is fixed.

**Comment by Thefluffypvper1** [comment]
I tested the loader on my dev server with silk spawners load at y 255 and spawners at y 64 and it worked, (On 1.8.8 paper)

**Comment by OmerBenGera** [comment]
> 
> 
> I tested the loader on my dev server with silk spawners load at y 255 and spawners at y 64 and it worked, (On 1.8.8 paper)

now try switching to Winespigot, let me know if it works or not.
If it doesn't, then it's a conflict with Winespigot.

**Comment by Thefluffypvper1** [comment]
The test I conducted was on paper 1.8.8 using cloudspawners and wildloaders I put the loader at Y  255 and spawners like at Y 66 and the spawners didn't load with the loader up at the y high, but when its near the  spawner it loads it.

**Comment by OmerBenGera** [comment]
Try it without CloudSpawners, maybe it conflicts.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Thefluffypvper1** [comment]
So i tested with winespigot and silkspawners and a loader at y 255 and the spawners at y 69 and the spawners where not being loaded

**Comment by OmerBenGera** [comment]
I will look into that.
What type of spawner did you try?

**Comment by Thefluffypvper1** [comment]
I tested it on a pig spawner

**Comment by Thefluffypvper1** [comment]
Hows progress?

**Comment by OmerBenGera** [comment]
I tested it on my Paper 1.8.8 server and it works as it should.

**Comment by Thefluffypvper1** [comment]
I think you have to add support to winespigot for spawners to load in the hole chunk

**Comment by OmerBenGera** [comment]
> 

Does it work with Paper?

**Comment by Thefluffypvper1** [comment]
Yes cloudspawers and silkspawners got loaded by the loader within that one chunk

**Comment by OmerBenGera** [comment]
> Yes cloudspawers and silkspawners got loaded by the loader within that one chunk

In order to add support for it, I need a copy of the jar.
What is your discord? I will open a private channel for you so you can send it there.

**Comment by Thefluffypvper1** [comment]
Thefluffypvper#4520 This is my discord username please msg what jar you need if i can find a API i will send it to you

**Comment by Thefluffypvper1** [comment]
Could you please tell me your discord tag so I remember which one is you please.

**Comment by OmerBenGera** [comment]
I tried it with WineSpigot and it seems to work fine for me.
Try using default files on a new setup please, let me know if it works.
Maybe there's a specific configuration option that breaks it.

**Comment by OmerBenGera** [comment]
After another test and a bit of talk with you, I seemed to be able to replicate the issue.
I am in a talk with the developers of WineSpigot, hopefully we will be able to get into fixing it soon.

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it's fixed

**Comment by Thefluffypvper1** [comment]
https://www.youtube.com/watch?v=97PtpowCW8M&ab_channel=Doooch ye its still having the problem with loading the chunk, I was in gm 3 to unload the chunk and had a loader above my to see if it still loads the spawners but didn't work

**Comment by OmerBenGera** [comment]
I will look into that again.

**Comment by OmerBenGera** [comment]
The issue with monsters that they despawn if there aren't any players nearby, even if the chunk is loaded
Try it with animals, let me know if it works (I tested it again and it seems to work with animals)

**Comment by Thefluffypvper1** [comment]
https://gyazo.com/80e49c76d240093f60473d43c3dedb73 I tested it with pig and it didn't work

**Comment by OmerBenGera** [comment]
I really don't know what to tell you, it works fine for me using WineSpigot and WildLoaders...
Also they haven't changed anything in that matter besides some optimizations they added...

**Comment by Thefluffypvper1** [comment]
Could you please record how you tested it and send me the link

**Comment by OmerBenGera** [comment]
> Could you please record how you tested it and send me the link

I put a loader at the top of the world, then placed a spawner at Y60~ of pigs, then changed my gamemode to spectator and I watched them spawning.

**Comment by Thefluffypvper1** [comment]
Could you please try completely move away from the chunk and use a zombie or skeleton?

**Comment by OmerBenGera** [comment]
> Could you please try completely move away from the chunk and use a zombie or skeleton?

It will not work with zombies and skeletons, as they will despawn, as I said before.

**Comment by Thefluffypvper1** [comment]
https://www.youtube.com/watch?v=eJ98E3BN4Y4&ab_channel=Doooch this is my test btw with pigspawner

**Comment by Thefluffypvper1** [comment]
> > Could you please try completely move away from the chunk and use a zombie or skeleton?
> 
> It will not work with zombies and skeletons, as they will despawn, as I said before.

https://www.youtube.com/watch?v=eJ98E3BN4Y4&ab_channel=Doooch this is my test btw with pigspawner

**Comment by OmerBenGera** [comment]
You already sent it, there is no need to spam the issue with the same message.
Be patient and I will look at it once I can.

**Comment by OmerBenGera** [comment]
> > > Could you please try completely move away from the chunk and use a zombie or skeleton?
> > 
> > 
> > It will not work with zombies and skeletons, as they will despawn, as I said before.
> 
> https://www.youtube.com/watch?v=eJ98E3BN4Y4&ab_channel=Doooch this is my test btw with pigspawner

Sorry for the long waiting time.
You noticed that as soon as you got in spectator, the pig dispawned..?
This is the exact issue I mentioned above. Your mobs are dispawning if they don't have a player nearby (chunk loader acts as a player), which is why it occurs.
For hostile mobs, it's vanilla. For animals however, it's something else that causes this to happen. Find what is it and get rid of it.

**Comment by Thefluffypvper1** [comment]
> > > > Could you please try completely move away from the chunk and use a zombie or skeleton?
> > > 
> > > 
> > > It will not work with zombies and skeletons, as they will despawn, as I said before.
> > 
> > 
> > https://www.youtube.com/watch?v=eJ98E3BN4Y4&ab_channel=Doooch this is my test btw with pigspawner
> 
> Sorry for the long waiting time. You noticed that as soon as you got in spectator, the pig dispawned..? This is the exact issue I mentioned above. Your mobs are dispawning if they don't have a player nearby (chunk loader acts as a player), which is why it occurs. For hostile mobs, it's vanilla. For animals however, it's something else that causes this to happen. Find what is it and get rid of it.

So you believe a plugin is making them despawn?

**Comment by OmerBenGera** [comment]
> > > > > Could you please try completely move away from the chunk and use a zombie or skeleton?
> > > > 
> > > > 
> > > > It will not work with zombies and skeletons, as they will despawn, as I said before.
> > > 
> > > 
> > > https://www.youtube.com/watch?v=eJ98E3BN4Y4&ab_channel=Doooch this is my test btw with pigspawner
> > 
> > 
> > Sorry for the long waiting time. You noticed that as soon as you got in spectator, the pig dispawned..? This is the exact issue I mentioned above. Your mobs are dispawning if they don't have a player nearby (chunk loader acts as a player), which is why it occurs. For hostile mobs, it's vanilla. For animals however, it's something else that causes this to happen. Find what is it and get rid of it.
> 
> So you believe a plugin is making them despawn?

It might be a plugin or a custom configuration of WineSpigot which makes animals (pigs, cows, etc) to despawn if there are no nearby players, similar to how hostiles do. Might be a bug with WineSpigot, who knows.

**Comment by FourNineRugz** [comment]
@OmerBenGera I have this same issue except with RoseSpawners. I have spawners that are withinh the 5x5 chunk radius but if it's too high or low the spawners won't load

**Comment by OmerBenGera** [comment]
> @OmerBenGera I have this same issue except with RoseSpawners. I have spawners that are withinh the 5x5 chunk radius but if it's too high or low the spawners won't load

Open a new issue regarding this :)
