### ISSUE TITLE
Maximuim String Length Kick

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildLoaders#31]
### Minecraft's Version

1.16.5 and server jar is paper-1.16.5-790.jar

### Plugin's Version

WildLoaders-1.0.1-b18.jar

### Describe the bug

Players that are opped are getting kicked due to max string length as shown in the image below, when standing next to a player with a longish username then the op player gets kicked, which only seems to occur to them.
![image](https://user-images.githubusercontent.com/19984107/141332941-e7db30af-d463-452e-9bc9-bfb40a7a9432.png)

Only seems to occur when a player with opped player accounts is standing near a loader when a player has a longish username.

### To Reproduce

Stand next to a player with a long username, with a loader placed down, preferably with a 30-day large loader placed down. 

### Additional Information

![image](https://user-images.githubusercontent.com/19984107/141333419-c2becaa5-d0e7-4aff-8886-2775e90f3252.png)

**Comment by OmerBenGera** [comment]
How is it related to the plugin?

**Comment by DJDan21** [comment]
Cause some as I removed the plugin that message stopped happening.

**Comment by OmerBenGera** [comment]
> Cause due as I removed the wildloaders that message stopped happening.

I understand.
I will look into that.

**Comment by OmerBenGera** [comment]
Check out latest build, should be fixed.

**Comment by DJDan21** [comment]
For some reason, I can see the NPCs with an opped account?
![image](https://user-images.githubusercontent.com/19984107/141595174-fc4fd805-ceb6-478d-b4dc-dfc5e4a31441.png)

So far I haven't experienced the issue with getting, but I report back if I do.

**Comment by OmerBenGera** [comment]
You can see them due to a mod probably, as these are not real players and they are hidden from players.
I am closing this for now, if it occurs again lmk here
