### ISSUE TITLE
Issue with hover-over text.

### ISSUE THREAD

**Issue by SleepyCatten** [BG-Software-LLC/WildLoaders#35]
### Minecraft's Version

Minecraft 1.18.1, running on a Paper server (Paper version git-Paper-163).

### Plugin's Version

WildLoaders-1.0.3-b33

### Describe the bug

On hovering-over the item in your inventory, the text is too long to fit on the screen, causing it to be pushed off the screen.

### To Reproduce

1. Give yourself a chunk loader.
2. Hover over it in your inventory.

### Additional Information

![image](https://user-images.githubusercontent.com/92794563/150375509-b4c64a93-156a-4879-ad40-f9a70a86d165.png)

**Comment by OmerBenGera** [comment]
Split the text to a different line, it's configurable.
