### ISSUE TITLE
Sometimes you cant place anything next to a chunk loader. It's as if something invisible is there.

### ISSUE THREAD

**Issue by FourNineRugz** [BG-Software-LLC/WildLoaders#37]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/17154368/154125471-e8df3989-9ecb-4029-8bbc-67b34940b04f.png)

### Plugin's Version

1.0.3

### Describe the bug

Sometimes you cant place anything next to a chunk loader. It's as if something invisible is there.

### To Reproduce

![image](https://user-images.githubusercontent.com/17154368/154125379-9a5cbb29-0506-4189-a40f-c9ae2dc603da.png)

**Comment by OmerBenGera** [comment]
Sorry for the long waiting time, it's fixed in latest dev build
