### ISSUE TITLE
WildLoaders is getting disabled by server start.

### ISSUE THREAD

**Issue by JaNOriginalDe** [BG-Software-LLC/WildLoaders#40]
### Minecraft's Version

Minecraft: 1.18.2 | Server: paper-1.18.2-290.jar

### Plugin's Version

WildLoaders-1.1.0.jar

### Describe the bug

The Problem is that the Plugin is getting diasbled at the server startup. It happened at some time idk why.

### To Reproduce

As mentioned idk why it happens.

### Additional Information

https://pastebin.com/1JcCD4g5

**Comment by OmerBenGera** [comment]
Next time, upload the logs to pastebin and don't send them here.

Upload your config file to pastebin and send it here please.

**Comment by OmerBenGera** [comment]
Any news regarding this?
