### ISSUE TITLE
Feature Request "I would love for a plugin to be supported"

### ISSUE THREAD

**Issue by Michael-A-Sloan** [BG-Software-LLC/WildLoaders#43]
### Minecraft's Version

Paper Latest

### Plugin's Version

any

### Describe the bug

No bug just a feature request for a Plugin named "Lands" to be supported if possible.

### To Reproduce

none

**Comment by OmerBenGera** [comment]
How can it be supported?

**Comment by OmerBenGera** [comment]
Added in latest dev build
