### ISSUE TITLE
1.19 Experimental Builds 

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/WildLoaders#44]
This issue is a global issue to report bugs related to the 1.19 experimental builds.

You can find the experimental builds on https://hub.bg-software.com/job/1.19%20Experimental%20Builds/

**Comment by SmokinShark** [comment]
After Server Restart the Loader Block turns into a normal Block without beeing an Loader anymore.

**Comment by OmerBenGera** [comment]
> After Server Restart the Loader Block turns into a normal Block without beeing an Loader anymore.

Check out the new build, let me know if it works now.
If it doesn't, look for errors and post them here via pastebin.

**Comment by SmokinShark** [comment]
> Check out the new build, let me know if it works now. If it doesn't, look for errors and post them here via pastebin.
Startet working after realoaded the Plugins (uploaded b2 and deleted b1 before ofc) already and keep work after restarting the Server. Thx!

**Comment by SmokinShark** [comment]
> Author

Startet working after realoaded the Plugins (uploaded b2 and deleted b1 before ofc) already and keep work after restarting the Server. Thx!

**Comment by SmokinShark** [comment]
> Check out the new build, let me know if it works now. If it doesn't, look for errors and post them here via pastebin.

Startet working after realoaded the Plugins (uploaded b2 and deleted b1 before ofc) already and keep work after restarting the Server. Thx!

**Comment by SmokinShark** [comment]
> Check out the new build, let me know if it works now. If it doesn't, look for errors and post them here via pastebin.

Started working after reloaded the Plugins (uploaded b2 and deleted b1 before ofc) already and keep work after restarting the Server. Thx!
