### ISSUE TITLE
Loader disabled after Server Restart on Spigot 1.19

### ISSUE THREAD

**Issue by SmokinShark** [BG-Software-LLC/WildLoaders#45]
### Minecraft's Version

Spigot 1.19

### Plugin's Version

WildLoaders-1.1.1-b1 (Experimental Build)

### Describe the bug

After Server Restart the Loader Block turns into a normal Block without beeing an Loader anymore.

### To Reproduce

Place a Loader and restart the Server.

**Comment by OmerBenGera** [comment]
Report it on the 1.19 Issue that I already created: #44
