### ISSUE TITLE
Server stop when wildloader out of time

### ISSUE THREAD

**Issue by novaechiro** [BG-Software-LLC/WildLoaders#47]
### Minecraft's Version

spigot 1.16.5

### Plugin's Version

1.2.0

### Describe the bug

when the chunk loader out of time, the server stop

### To Reproduce

give a wildloader 10 seconds
place down
10 seconds later, the server crash

### Additional Information

https://pastebin.pl/view/6bf9e81d

**Comment by OmerBenGera** [comment]
What version of Spigot are you using?
Give me the exact value of /version.

**Comment by OmerBenGera** [comment]
> https://getbukkit.org/get/RD0y91OTotryPrElNQe4ovBLDNweoO5Z
> 
> I use spigot 1.16.5 and here is the link where i download it

Download 1.16.5 from Spigot.
WildLoaders only supports spigot and its forks

**Comment by novaechiro** [comment]
although the webpage is getbukkit but the version there is spigot 1.16.5
![image](https://user-images.githubusercontent.com/61116567/175802630-c2aa47f6-df4c-4fca-9476-fc04f91fde5b.png)

**Comment by OmerBenGera** [comment]
> although the webpage is getbukkit but the version there is spigot 1.16.5 ![image](https://user-images.githubusercontent.com/61116567/175802630-c2aa47f6-df4c-4fca-9476-fc04f91fde5b.png)

What version then do you use?
Send me the output of /version

**Comment by novaechiro** [comment]
![image](https://user-images.githubusercontent.com/61116567/176078528-d58b10d1-f189-499d-a829-7e98a135a891.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
