### ISSUE TITLE
Could not pass event BlockPlaceEvent to WildLoaders

### ISSUE THREAD

**Issue by FadingFog** [BG-Software-LLC/WildLoaders#54]
### Minecraft's Version

1.7.10 Thermos

### Plugin's Version

1.2.0 + 1.2.0 b53

### Describe the bug

When I put the block an error occurs "Could not pass event BlockPlaceEvent to WildLoaders v1.2.0.53"

### To Reproduce

Place the loader...

### Additional Information

https://pastebin.com/D6NhMWFc

**Comment by OmerBenGera** [comment]
Only spigot and its forks are supported

**Comment by FadingFog** [comment]
Thermos actually uses Spigot...

**Comment by FadingFog** [comment]
> Only spigot and its forks are supported

Thermos actually uses Spigot...

**Comment by FadingFog** [comment]
> It doesnt.

https://github.com/CyberdyneCC/Thermos

**Comment by FadingFog** [comment]
So it's not a Spigot fork at all. This is the server core that uses Spigot

**Comment by OmerBenGera** [comment]
> So it's not a Spigot fork at all. This is the server core that uses Spigot. It's fork of the Cauldron (formerly MCPC)

Trust me, if I could support it I would. The issue is the plugin uses nms (minecraft's code) for some fuctionalities, and because of the obfuscated code of your jars, its just not possible to support it.
