### ISSUE TITLE
Chunk Loader doesn’t load the whole chunk 

### ISSUE THREAD

**Issue by xCab6** [BG-Software-LLC/WildLoaders#58]
### Minecraft's Version

1.8

### Plugin's Version

The latest one from mcm

### Describe the bug

If you have spawners at like Y255 and the chunk loader at y200, the spawners will not be loaded. The loader has to be in the afk radius in order to load the spawners. Can you make it where it loads the whole chunk from bedrock to sky limit.

### To Reproduce

Make the chunk loader load the whole chunk from bedrock to sky limit instead of the 16 block radius the loader is placed in.

### Additional Information

Don’t really have anything else other than we have a factions map releasing nest Saturday and would love for this to be fixed by then!

**Comment by xCab6** [comment]
For the jar we’re using WineSpigot and also silked spawners

**Comment by OmerBenGera** [comment]
I tested it and it works fine for me.
Make sure you:
A) Use latest dev build from https://bg-software.com/wildloaders.
B) Don't test it with hostile mob spawners. Hostile mobs despawn if there are no players nearby, no matter if the chunk is loaded or not.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still occurs, let me know
