### ISSUE TITLE
Wild Loaders Not Working after Server Reboots

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildLoaders#61]
### Minecraft's Version

1.8.8 and BeerSpigot

### Plugin's Version

WildLoaders-1.2.1-b60

### Describe the bug

Placed down chunk loaders turning into a beacon or the material you have set into the config, which no longer has the hologram after the server has performed a server reboot

### To Reproduce

Place down a chunk loader
Check back on the chunk loader after you have restarted your Minecraft server

### Additional Information

Here is my current config: https://pastebin.com/1ySTmJy2

**Comment by DJDan21** [comment]
Here is the latest server log https://pastebin.com/HFYL7mmx which i forgot to add

**Comment by OmerBenGera** [comment]
Seems like an incompatibility issue with BeerSpigot.
There are errors when a chunk loader is placed that you missed.

**Comment by DJDan21** [comment]
Yes there is an error that i didn't know about in the logs which is here https://pastebin.com/1BpQDGya

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
