### ISSUE TITLE
Server crashing with this error

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildLoaders#62]
### Minecraft's Version

Paper 1.19.2 #194

### Plugin's Version

2022.7

### Describe the bug

Server crashed and the crash report had this error in it: https://pastebin.com/AQCLhhCT

### To Reproduce

Unknown

**Comment by OmerBenGera** [comment]
I can't replicate the issue - the error doesn't seem to occur for me.

**Comment by ArmonicPvP** [comment]
This was actually happening because of a memory leak from MythicLib. Thanks
