### ISSUE TITLE
Chunk loaders can earn Surge Protector achievement

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildLoaders#63]
### Minecraft's Version

Paper 1.19.2 #194

### Plugin's Version

2022.7

### Describe the bug

Chunk loaders can get the Surge Protector achievement

### To Reproduce

Place villager, place lightning rod around 10 blocks away in the air to not cause fire, then start thunderstorm and the chunk loaders placed nearby will earn the Surge Protector achievement

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
