### ISSUE TITLE
Unable to get the specified number of Loaders

### ISSUE THREAD

**Issue by Iverins** [BG-Software-LLC/WildLoaders#65]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/30949525/213919693-546917dc-ae9e-4ad6-bcff-f5e390e6eebd.png)

### Plugin's Version

Dev #69

### Describe the bug

/loader give Iverins_ normal_loader 60 1
Only give a Loader that lasts for one second
As per your description, it should give 60 Loaders.

### To Reproduce

/loader give Iverins_ normal_loader 60 1
Only give a Loader that lasts for one second
As per your description, it should give 60 Loaders.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
