### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by liyola** [BG-Software-LLC/WildLoaders#67]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1

### Describe the bug

server crash on placing

### To Reproduce

the moment u place a loader the server crashes

**Comment by OmerBenGera** [comment]
Upload your server logs to pastebin and send a link to it here

**Comment by Powershooter83** [comment]
Hey, I have the same problem in the 1.19.4.. 
I would otherwise add my crash reports here as well:
https://pastebin.com/5V81CAZQ
https://pastebin.com/QPjfVaaX
(I hope I do not disturb you with my logs)

**Comment by OmerBenGera** [comment]
> Hey, I have the same problem in the 1.19.4.. I would otherwise add my crash reports here as well: https://pastebin.com/5V81CAZQ https://pastebin.com/QPjfVaaX (I hope I do not disturb you with my logs)

Update to latest dev build, let me know if it is fixed.

**Comment by Powershooter83** [comment]
The latest dev build has fixed it, thanks for the help!

**Comment by MrMineToons** [comment]
Hello! I had same problem.
The latest dev build fixed it, but there is a bug.

I placed a Large Loader, and tried to sleep. When sleeping, all the animation goes right, but when animation finish, we wake up and time hasnt changed. Basically always you sleep, time doesnt change, you just wake up. There is no error in console...

When I try several times to sleep, it starts to throw error but for other plugins, like Realistic Seasons...
When I remove the Large Loader, I can sleep successfuly, when the sleeping animations finish, time has changed.

**Comment by OmerBenGera** [comment]
> Hello! I had same problem. The latest dev build fixed it, but there is a bug.
> 
> I placed a Large Loader, and tried to sleep. When sleeping, all the animation goes right, but when animation finish, we wake up and time hasnt changed. Basically always you sleep, time doesnt change, you just wake up. There is no error in console...
> 
> When I try several times to sleep, it starts to throw error but for other plugins, like Realistic Seasons... When I remove the Large Loader, I can sleep successfuly, when the sleeping animations finish, time has changed.

Open a new issue regarding this, as it is not related to the original issue in any way.
