### ISSUE TITLE
1.16.5 | Issue with loaders and spawners while players are offline

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/WildLoaders#7]
Hey!

I recently noticed the loaders don't work with spawners while players are offline. I ran some tests before deploying the plugin on my prod server, and actually found that, the loader work flawlessly with superiorskyblock and farms, even tho I'm offline, but they don't work at all with spawners.

The server is under purpur-1016 (1.16.5), and I use SuperiorSkyblock2-b93, WildLoaders-b7, WildStacker-b89, and zSpawner PRE-3.0.1.7. Afaik the plugin doesn't change anything spawner behaviors, it's just a spawner management plugin. Another user reported the same issue on discord with SSB2, WildLoaders and RoseStacker.

**Comment by OmerBenGera** [comment]
When you're not online, mobs might despawn - maybe that's the issue.
Try it using mobs that don't despawn, such as cows or pigs.

**Comment by OmerBenGera** [comment]
I couldn't seem to replicate the issue, everything seems to work for me just fine

**Comment by ElBananaa** [comment]
> I couldn't seem to replicate the issue, everything seems to work for me just fine

That's pretty weird. I don't really understand why it doesn't work for me.
Is it supposed to work, even with disabled redstone in superiorskyblock2 config file?
I don't know if this can be caused by zSpawner, the plugin already supports ssb2 according to the dev.

**Comment by OmerBenGera** [comment]
Check if it works with only WS installed

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ElBananaa** [comment]
Hey!
Sorry, I completely lost the track about this. I'll try it later tonight.

**Comment by ElBananaa** [comment]
Alright, so after testing it, the loader works correctly with redstone and spawners without any other plugin, on a fresh install with the latest version of purpur.
I then installed SSB2 b126, set `disable-redstone-offline: true`, `disable-redstone: true` and `disable-spawning: true` and now, redstone and spawners aren't loaded anymore, so I can confirm this is related to SSB2.

**Comment by OmerBenGera** [comment]
That's intended, as these things don't support WildLoaders.

**Comment by ElBananaa** [comment]
> That's intended, as these things don't support WildLoaders.

Oh, ok, that's kinda sad tho. Do you plan to add support for these options?

**Comment by OmerBenGera** [comment]
> 
> 
> > That's intended, as these things don't support WildLoaders.
> 
> Oh, ok, that's kinda sad tho. Do you plan to add support for these options?

I am not adding new features, PR are welcomed tho
