### ISSUE TITLE
loaders (hologram-lines)

### ISSUE THREAD

**Issue by TwitterTOS** [BG-Software-LLC/WildLoaders#70]
### Minecraft's Version

1.8.8, spigot

### Plugin's Version

dev build from 13/april

### Describe the bug

![](https://cdn.discordapp.com/attachments/751895102422777886/1110337578160361534/image.png)

it will only show the bottom line on the hologram, meaning the timer

### To Reproduce

just place down the loader, you will see only the timer not the first line

### Additional Information

Could you also please add a placeholder for name of the loader

  large_loader:
    time: 86400
    type: BEACON
    chunks-radius: 2 # This will load all chunks in a radius of 2, aka 5x5 chunks
    name: '&6Large Chunk Loader &7(Place to load)'
    lore:
      - '&7Place this chunk loader to keep all chunks'
      - '&7in a radius of 2 loaded in the next {}!'

for example in this case {loader-name} would be "Large Chunk Loader", or something like this so in the holograms this can be shown as 

# Hologram lines for regular chunk loaders.

hologram-lines:

- '&b{1}''s {loader-name} Loader'
- '&bTime Left: &f{1} days, {2} hours, {3} minutes, {4} seconds'

**Comment by TwitterTOS** [comment]
https://prnt.sc/OxUue8jpNlEN

**Comment by TwitterTOS** [comment]
now i got no holo lines

**Comment by TwitterTOS** [comment]
https://prnt.sc/bbY0CVdxfVIg

**Comment by OmerBenGera** [comment]
Send me what `/version` shows you. I need your server version, not the plugin's version.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
