### ISSUE TITLE
Doesn't work with WildStacker

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildLoaders#72]
### Minecraft's Version

1.18.2

### Plugin's Version

2023.1-b1

### Describe the bug

The plugin used to work with WildStacker while being offline, but doesn't seem like it's working. I'm also using WildChest for the farm.

### To Reproduce

-

**Comment by OmerBenGera** [comment]
What does not work exactly?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
