### ISSUE TITLE
Entity that does not despawn

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/WildLoaders#74]
### Minecraft's Version

Paper 1.19.4

### Plugin's Version

2023.2

### Describe the bug

Entities do not despawn in a loaded chunk

### To Reproduce

Spawn Mob in a Chunk Loader

**Comment by OmerBenGera** [comment]
The chunk is kept loaded, why would they despawn?

**Comment by Xitryne** [comment]
Yes, but after 5 or 10m aren't the entities supposed to despawn?

**Comment by OmerBenGera** [comment]
If the chunk is loaded and you're near it or any other plugin, then no.
Because the loaders act as players in some ways, then it sounds fine for me.

If it wouldn't be the case, entities would instantly despawn (monster entities at least)

**Comment by Xitryne** [comment]
I see, and would it be possible to add an option for the Chunk Loader to force the dispawn after a while? Because I use WildStacker's clear to counteract this.

**Comment by Xitryne** [comment]
Also I noticed, I don't know if it's a bug but mobs don't appear naturally in the presence of a Chunk Loader, only generator mobs appear.

**Comment by OmerBenGera** [comment]
Sadly not, this makes no sense as a feature.
The chunk is loaded as any other chunk in the server, and therefore entities inside it will not be despawned.
