### ISSUE TITLE
Wildloader don't keep sell chest from wildchests active

### ISSUE THREAD

**Issue by SpYoXDOT** [BG-Software-LLC/WildLoaders#76]
### Minecraft's Version

1.19.4

### Plugin's Version

WildLoaders-2023.2.jar

### Describe the bug

When i put a chunk loader the spawner and crops is active by the chunk loader but the chunk loader don't keep the sell chest active so the player don't received money because the sell chest don't sell anything

### To Reproduce

You put some spawner and some block for the mobs when they fall they die and sell chest and one chunk loader and you will see it don't sell if you'r not here when you will come back on your server you will see a lot of items they are not sell

**Comment by OmerBenGera** [comment]
I did a similar experience, but with hoppers and diamonds.
Hoppers move items into the sell chests, then I log out, and I see that I still get money.
Does it work for you as well?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
