### ISSUE TITLE
Could not pass PlayerJoinEvent WildLoaders(1.20.2)

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildLoaders#78]
### Minecraft's Version

1.20.2 and TequilaSpigot(Paper fork)

### Plugin's Version

2023.3

### Describe the bug

Error when player joins
https://mcpaste.io/4f4ed829ba397ca9

### To Reproduce

Just install paper latest upstream maybe? and check, idk but please fix the error.

### Additional Information

https://mcpaste.io/0c76807a22dc5225

whole server log

**Comment by OmerBenGera** [comment]
Report it to Paper.
This is bug in the Bukkit API, not the plugin.
