### ISSUE TITLE
Wild Loaders (Bugging out)

### ISSUE THREAD

**Issue by TwitterTOS** [BG-Software-LLC/WildLoaders#79]
### Minecraft's Version

1.8.8 Minecraft version, when the loaders are first placed they work perfectly fine as their supposed to. however after a few hours NOT ALWAYS sometimes in some chunks the hologram dissapears and the chunk is stopped loading and when i break the beacon and try to place another one on top it just breaks the beacon AUTOMATICALLY and i can't place anything on that block anymore. I have to clear the database.db everytime and put down all the loaders again

### Plugin's Version

latest dev build

### Describe the bug

1.8.8 Minecraft version, when the loaders are first placed they work perfectly fine as their supposed to. however after a few hours NOT ALWAYS sometimes in some chunks the hologram dissapears and the chunk is stopped loading and when i break the beacon and try to place another one on top it just breaks the beacon AUTOMATICALLY and i can't place anything on that block anymore. I have to clear the database.db everytime and put down all the loaders again

### To Reproduce

im not entirely sure, it just randomly happens

### Additional Information

contact me on discord for more information, available to go in call @waltertos

**Comment by OmerBenGera** [comment]
Does it happen maybe after the loader is timed out?
Also, are there any errors on console?

**Comment by TwitterTOS** [comment]
i haven't seen any errors in the console and no the loader is not "timed out", i haven't specified how long it should run for, so it should just run forever (what ive been told) and it works fine sometimes and than some randomly just break.

**Comment by OmerBenGera** [comment]
Find out how to replicate the issue, as I cannot fix an issue that no one knows how it happens, or when it happens.

**Comment by TwitterTOS** [comment]
https://prnt.sc/P5BKkbGCJCII , someone broke a chunk loader, and now its broken like its doing the following.

https://prnt.sc/CSvSkfWDkMhY

**Comment by TwitterTOS** [comment]
also when this happens, the chunk becomes glitched and no mobs can spawn in it, even if the player is in the chunk. im not sure how to recreate it

**Comment by OmerBenGera** [comment]
> https://prnt.sc/P5BKkbGCJCII , someone broke a chunk loader, and now its broken like its doing the following.
> 
> https://prnt.sc/CSvSkfWDkMhY
> 
> also when this happens, the chunk becomes glitched and no mobs can spawn in it, even if the player is in the chunk. im not sure how to recreate it, if its possible for you to send me a version with some flags, i can let you know the output next time this happens, cause it seems nothing goes to console either

Open a new issue regarding this.
Make sure you let me know how to replicate the issue

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
