### ISSUE TITLE
Add a metadata to fake players so external plugins can detect them

### ISSUE THREAD

**Issue by SkytAsul** [BG-Software-LLC/WildLoaders#82]
### Minecraft's Version

1.20.4

### Plugin's Version

2023.3

### Describe the bug

Not a bug, but you told me to open an issue and that's the only template I am allowed to choose.
Anyway, it's related to this discussion: https://github.com/BG-Software-LLC/WildLoaders/discussions/81
`Bukkit#getPlayers` maybe does not return your NPCs, but some player events are still fired with the NPCs.
The "NPC" metadata is quite common (Citizens does it, for instance) so that would be nice to add, and it does not have any drawback afaik.

### To Reproduce

nothing

**Comment by OmerBenGera** [comment]
Which events are fired?
I want to get rid of them, and I will also add the metadata.

**Comment by SkytAsul** [comment]
I cannot tell exactly. I will get back to you once the user that reported the bug in my plugin answers.
In the meantime yeah it would be nice to have the metadata.

**Comment by OmerBenGera** [comment]
Have you looked into the events that are fired?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SkytAsul** [comment]
Sorry, I've got no response about it. I will try to reproduce and let you know.

**Comment by SkytAsul** [comment]
I've succeeded in reproducing the problem: it is caused by `World#getPlayers()` returning a collection containing WildLoaders fake players.

**Comment by OmerBenGera** [comment]
Check out latest dev build, NPCs should now have the "NPC" metadata.

**Comment by SkytAsul** [comment]
Thank you!

**Comment by OmerBenGera** [comment]
Let me know if that all what you need and that it works

**Comment by SkytAsul** [comment]
Sorry not to have answered before, it works! Thank you very much.
