### ISSUE TITLE
WildLoaders Database Server Shutdown Error

### ISSUE THREAD

**Issue by DJDanTheMan** [BG-Software-LLC/WildLoaders#85]
### Minecraft's Version

1.20.1 and server jar Paper-196

### Plugin's Version

WildLoaders v2023.3-b10

### Describe the bug

https://pastebin.com/WrdVaesm

### To Reproduce

Unsure how to reduce it randomly accrued

### Additional Information

Here is the full server log at the time when this error accused https://pastebin.com/Fn5sfFsX

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue continues let me know
