### ISSUE TITLE
loader despawn

### ISSUE THREAD

**Issue by naksha1** [BG-Software-LLC/WildLoaders#87]
### Minecraft's Version

1.20.1 paper

### Plugin's Version

wild loader 2023.3

### Describe the bug

loader get despawn 

### To Reproduce

i place the loader in farm and go to the nether when i back i saw the loader get despawn

**Comment by OmerBenGera** [comment]
Chunk loaders have timeout, and after the timeout is reached, they will be broken.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SkytAsul** [comment]
I've succeeded in reproducing the problem: it is caused by `World#getPlayers()` returning a collection containing WildLoaders fake players.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
