### ISSUE TITLE
WildLoaders causing Exception ticking world

### ISSUE THREAD

**Issue by DJDanTheMan** [BG-Software-LLC/WildLoaders#88]
### Minecraft's Version

1.20.1 and Paper-196

### Plugin's Version

v2023.3-b11

### Describe the bug

I am not sure but it is causing errors and crashed my server. I will provide the error that it shows in the console before the server crashed https://pastebin.com/kpPfkB8t and I will also provide the crash report https://pastebin.com/xC6wqkM9

### To Reproduce

Im not sure

### Additional Information

Crash Report: https://pastebin.com/xC6wqkM9
Error: https://pastebin.com/kpPfkB8t

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know
