### ISSUE TITLE
2 blocks are dropped after breaking loader

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/WildLoaders#99]
### Minecraft's Version

Purpur-2176 (1.20.4)

### Plugin's Version

2024.1

### Describe the bug

When you place loader and then break it, 2 block will be dropped - Loader and normal block equivalent of loader.

### To Reproduce

Place loader (type: BEACON), and when you break it you will get loader back and normal beacon block.

**Comment by OmerBenGera** [comment]
I cannot replicate the issue
I suspect another plugin somehow conflicts with it.

Can you replicate it on a server with only WildLoaders installed?

**Comment by Envqu** [comment]
Yes, sorry, my bad. Plugin with autopickup did something wrong.
